/** @type {import("stylelint").Config} */
export default {
  extends: ["stylelint-config-standard-scss"],
  plugins: [
    "stylelint-order",
    "stylelint-declaration-block-no-ignored-properties",
    "@stylistic/stylelint-plugin",
  ],
  customSyntax: "postcss-scss",
  rules: {
    "@stylistic/indentation": 2,
    "@stylistic/string-quotes": "double",
    "@stylistic/declaration-colon-space-after": "always-single-line",
    "@stylistic/declaration-colon-space-before": "never",
    "@stylistic/block-opening-brace-space-before": "always",
    "@stylistic/declaration-block-trailing-semicolon": "always",
    "declaration-property-value-disallowed-list": {},
    "plugin/declaration-block-no-ignored-properties": true,
    "order/order": [
      {
        type: "at-rule",
        name: "use",
      },
      {
        type: "at-rule",
        name: "forward",
      },
      {
        type: "at-rule",
        name: "include",
        hasBlock: false,
      },
      "dollar-variables",
      "custom-properties",
      "declarations",
      "rules",
      {
        type: "at-rule",
        name: "include",
        hasBlock: true,
      },
      "at-rules",
    ],
    "order/properties-order": [
      "display",
      "position",
      "inset",
      "top",
      "right",
      "bottom",
      "left",
      "z-index",
      "float",
      "clear",
      "visibility",
      "overflow",
      "overflow-x",
      "overflow-y",
      "clip-path",
      "flex",
      "flex-grow",
      "flex-shrink",
      "flex-basis",
      "flex-direction",
      "flex-wrap",
      "flex-flow",
      "order",
      "grid",
      "grid-template",
      "grid-template-columns",
      "grid-template-rows",
      "grid-template-areas",
      "grid-auto-columns",
      "grid-auto-rows",
      "grid-auto-flow",
      "grid-column",
      "grid-row",
      "grid-area",
      "place-items",
      "place-content",
      "place-self",
      "justify-content",
      "justify-items",
      "justify-self",
      "align-content",
      "align-items",
      "align-self",
      "gap",
      "row-gap",
      "column-gap",
      "container-type",
      "container-name",
      "box-sizing",
      "width",
      "min-width",
      "max-width",
      "height",
      "min-height",
      "max-height",
      "aspect-ratio",
      "padding",
      "padding-block",
      "padding-block-start",
      "padding-block-end",
      "padding-inline",
      "padding-inline-start",
      "padding-inline-end",
      "padding-top",
      "padding-right",
      "padding-bottom",
      "padding-left",
      "background",
      "background-color",
      "background-image",
      "background-position",
      "background-size",
      "background-repeat",
      "background-clip",
      "background-origin",
      "backdrop-filter",
      "color",
      "border",
      "border-top",
      "border-right",
      "border-bottom",
      "border-left",
      "border-radius",
      "border-top-left-radius",
      "border-top-right-radius",
      "border-bottom-right-radius",
      "border-bottom-left-radius",
      "box-shadow",
      "outline",
      "opacity",
      "filter",
      "mix-blend-mode",
      "font",
      "font-family",
      "font-size",
      "font-weight",
      "font-style",
      "font-variant",
      "line-height",
      "letter-spacing",
      "word-spacing",
      "text-align",
      "text-transform",
      "text-decoration",
      "text-shadow",
      "white-space",
      "word-break",
      "overflow-wrap",
      "hyphens",
      "content",
      "cursor",
      "pointer-events",
      "user-select",
      "touch-action",
      "resize",
      "transform",
      "transform-origin",
      "perspective",
      "perspective-origin",
      "backface-visibility",
      "transition",
      "transition-property",
      "transition-duration",
      "transition-timing-function",
      "transition-delay",
      "animation",
      "animation-name",
      "animation-duration",
      "animation-timing-function",
      "animation-delay",
      "animation-iteration-count",
      "animation-direction",
      "animation-fill-mode",
      "animation-play-state",
      "will-change",
      "contain",
      "content-visibility",
      "scroll-behavior",
      "scroll-snap-type",
      "scroll-snap-align",
      "scroll-margin",
      "scroll-padding",
    ],
    "selector-class-pattern": null,
    "scss/dollar-variable-pattern": null,
    "scss/at-mixin-pattern": null,
    "scss/percent-placeholder-pattern": "[a-z0-9]+(-[a-z0-9]+)*",
    "no-descending-specificity": null,
    "block-no-empty": null,
    "no-empty-source": null,
    "scss/no-global-function-names": null,
    "declaration-block-single-line-max-declarations": 1,

    "rule-empty-line-before": [
      "always",
      {
        except: ["first-nested"],
      },
    ],
    "comment-empty-line-before": [
      "always",
      {
        except: ["first-nested"],
      },
    ],
  },
};
