CREATE INDEX `idx_group_members_user_id` ON `group_members` (`user_id`);--> statement-breakpoint
CREATE INDEX `idx_group_members_group_id` ON `group_members` (`group_id`);--> statement-breakpoint
CREATE INDEX `idx_group_members_user_group` ON `group_members` (`user_id`,`group_id`);--> statement-breakpoint
CREATE INDEX `idx_group_members_role` ON `group_members` (`role`);--> statement-breakpoint
CREATE INDEX `idx_groups_owner_id` ON `groups` (`group_owner_id`);--> statement-breakpoint
CREATE INDEX `idx_groups_public` ON `groups` (`group_public`);--> statement-breakpoint
CREATE INDEX `idx_groups_status` ON `groups` (`group_status`);--> statement-breakpoint
CREATE INDEX `idx_groups_public_status` ON `groups` (`group_public`,`group_status`);--> statement-breakpoint
CREATE INDEX `idx_kit_categories_kit_id` ON `kit_categories` (`kit_id`);--> statement-breakpoint
CREATE INDEX `idx_kit_categories_category_id` ON `kit_categories` (`category_id`);--> statement-breakpoint
CREATE INDEX `idx_kit_categories_kit_category` ON `kit_categories` (`kit_id`,`category_id`);--> statement-breakpoint
CREATE INDEX `idx_kits_user_id` ON `kits` (`user_id`);--> statement-breakpoint
CREATE INDEX `idx_kits_group_id` ON `kits` (`group_id`);--> statement-breakpoint
CREATE INDEX `idx_kits_created_on` ON `kits` (`kit_created_on`);--> statement-breakpoint
CREATE INDEX `idx_kits_published_on` ON `kits` (`kit_published_on`);--> statement-breakpoint
CREATE INDEX `idx_kits_status` ON `kits` (`kit_status`);--> statement-breakpoint
CREATE INDEX `idx_kits_status_created` ON `kits` (`kit_status`,`kit_created_on`);--> statement-breakpoint
CREATE INDEX `idx_kits_user_status` ON `kits` (`user_id`,`kit_status`);--> statement-breakpoint
CREATE INDEX `idx_logins_user_id` ON `logins` (`user_id`);--> statement-breakpoint
CREATE INDEX `idx_logins_verification_code` ON `logins` (`login_verification_code`);--> statement-breakpoint
CREATE INDEX `idx_pad_samples_pad_id` ON `pad_samples` (`pad_id`);--> statement-breakpoint
CREATE INDEX `idx_pad_samples_sample_id` ON `pad_samples` (`sample_id`);--> statement-breakpoint
CREATE INDEX `idx_pad_samples_pad_order` ON `pad_samples` (`pad_id`,`playback_order`);--> statement-breakpoint
CREATE INDEX `idx_pads_kit_id` ON `pads` (`pad_kit_id`);--> statement-breakpoint
CREATE INDEX `idx_pads_kit_position` ON `pads` (`pad_kit_id`,`pad_position`);--> statement-breakpoint
CREATE INDEX `idx_pads_choke_group` ON `pads` (`pad_choke_group`);--> statement-breakpoint
CREATE INDEX `idx_samples_user_id` ON `samples` (`user_id`);--> statement-breakpoint
CREATE INDEX `idx_samples_group_id` ON `samples` (`group_id`);--> statement-breakpoint
CREATE INDEX `idx_samples_created_on` ON `samples` (`sample_created_on`);--> statement-breakpoint
CREATE INDEX `idx_samples_recent_created` ON `samples` (`sample_recent_created`);--> statement-breakpoint
CREATE INDEX `idx_samples_status` ON `samples` (`sample_status`);--> statement-breakpoint
CREATE INDEX `idx_samples_status_created` ON `samples` (`sample_status`,`sample_created_on`);--> statement-breakpoint
CREATE INDEX `idx_user_rights_user_id` ON `user_rights` (`user_id`);--> statement-breakpoint
CREATE INDEX `idx_user_settings_user_id` ON `user_settings` (`user_id`);--> statement-breakpoint
CREATE INDEX `idx_users_verified` ON `users` (`user_verified`);--> statement-breakpoint
CREATE INDEX `idx_users_name` ON `users` (`user_name`);