// ──────────────────────────────────────────────────────────────
// Imports
// ──────────────────────────────────────────────────────────────
import type { Database, Services } from "$/core";
import type { Tables } from "$/database/tables";
import { AdminService, AuthService, KitService, KitTransferService, UserService } from "$/services";
import { getKeyPair } from "$/services/auth";
import type { ServiceContainer } from "$/services/base";
import * as preferences from "@/preferences";

import { Hono } from "hono";

import { Kysely } from "kysely";
import { D1Dialect } from "kysely-d1";

import api from "./api";

/** Minimum bot score threshold (1-99). Lower = more likely bot. */
const BOT_SCORE_THRESHOLD = 30;

/** Wire up all services with container access and manager initialization */
function wireServices(container: ServiceContainer, env: Env): void {
  const factory = () => container;
  Object.values(container).forEach((service) => {
    service.setServices(factory);
    service.initializeManagers(env);
  });
}

// ──────────────────────────────────────────────────────────────
// Services Factory for Queue/Cron Handlers
// ──────────────────────────────────────────────────────────────

/**
 * Creates a fully initialized service container for use in queue handlers,
 * cron handlers, and other non-request contexts.
 *
 * @example
 * ```ts
 * // In a queue handler:
 * const services = await createServices(env);
 * await services.kit.deleteKit(kitId);
 * ```
 */
export async function createServices(env: Env): Promise<Services> {
  // Database setup
  const db: Database = {
    op: new Kysely<Tables>({
      dialect: new D1Dialect({ database: env.db }),
    }),
    cf: env.db,
  };

  // JWT key pair (static version for consistency)
  const keyPair = await getKeyPair(
    "RS256",
    env.JWT_PRIVATE_KEY,
    env.JWT_PUBLIC_KEY,
    "2025-01-04-v1",
  );

  // Create services
  const authService = new AuthService(db, keyPair);
  const userService = new UserService(db, env.MAILER_API_KEY);
  const kitService = new KitService(db);
  const kitTransferService = new KitTransferService(db);
  const adminService = new AdminService(db);

  // Wire up container
  const container: ServiceContainer = {
    admin: adminService,
    auth: authService,
    user: userService,
    kit: kitService,
    kitTransfer: kitTransferService,
  };

  wireServices(container, env);

  // Return Services interface (includes base + preferences)
  return {
    admin: adminService,
    auth: authService,
    base: authService,
    user: userService,
    kit: kitService,
    kitTransfer: kitTransferService,
    preferences,
  };
}

// Use the Env interface from worker-configuration.d.ts (auto-generated by Cloudflare)
export type Env = Cloudflare.Env;

/**
 * Creates and configures a Hono application with all services middleware.
 *
 * Sets up database connections (Kysely, Drizzle), authentication service,
 * and all business logic services. Each request gets access to these services
 * through the services middleware.
 *
 * @returns Configured Hono app instance with services and routes
 */
export function createApp() {
  const app = new Hono<{ Bindings: Env; Variables: { services: Services } }>();

  // ──────────────────────────────────────────────────────────────
  // Services Middleware
  // ──────────────────────────────────────────────────────────────
  // Provides database, auth, and service instances to all routes
  app.use(async (c, next) => {
    // ──────────────────────────────────────────────────────────────
    // Bot Management Check
    // ──────────────────────────────────────────────────────────────
    // Block requests with low bot score (not verified bots or static resources)
    const cf = c.req.raw.cf as IncomingRequestCfProperties | undefined;
    const botManagement = cf?.botManagement;

    if (botManagement) {
      const { score, verifiedBot, staticResource } = botManagement;
      if (score < BOT_SCORE_THRESHOLD && !verifiedBot && !staticResource) {
        return c.text("Access Denied", 403);
      }
    }

    // Create services using shared factory
    const services = await createServices(c.env);
    c.set("services", services);

    await next();
  });

  // ──────────────────────────────────────────────────────────────
  // API Routes
  // ──────────────────────────────────────────────────────────────
  // Mount all API routes at /api
  app.route("/api", api);

  return app;
}
